CURRENT_DIR = './'

download_map = {
    "2024": "https://datos.madrid.es/egob/catalogo/201200-10306320-calidad-aire-horario.zip",
    "2023": "https://datos.madrid.es/egob/catalogo/201200-10306319-calidad-aire-horario.zip",
    "2022": "https://datos.madrid.es/egob/catalogo/201200-10306318-calidad-aire-horario.zip",
    "2021": "https://datos.madrid.es/egob/catalogo/201200-10306317-calidad-aire-horario.zip",
    "2020": "https://datos.madrid.es/egob/catalogo/201200-10306316-calidad-aire-horario.zip",
    "2019": "https://datos.madrid.es/egob/catalogo/201200-42-calidad-aire-horario.zip",
    "2018": "https://datos.madrid.es/egob/catalogo/201200-10306314-calidad-aire-horario.zip",
    "2017": "https://datos.madrid.es/egob/catalogo/201200-10306313-calidad-aire-horario.zip",
    "2016": "https://datos.madrid.es/egob/catalogo/201200-28-calidad-aire-horario.zip",
    "2015": "https://datos.madrid.es/egob/catalogo/201200-27-calidad-aire-horario.zip",
    "2014": "https://datos.madrid.es/egob/catalogo/201200-26-calidad-aire-horario.zip",
    "2013": "https://datos.madrid.es/egob/catalogo/201200-23-calidad-aire-horario.zip",
    "2012": "https://datos.madrid.es/egob/catalogo/201200-22-calidad-aire-horario.zip",
    "2011": "https://datos.madrid.es/egob/catalogo/201200-21-calidad-aire-horario.zip",
    "2010": "https://datos.madrid.es/egob/catalogo/201200-20-calidad-aire-horario.zip",
    "2009": "https://datos.madrid.es/egob/catalogo/201200-19-calidad-aire-horario.zip",
    "2008": "https://datos.madrid.es/egob/catalogo/201200-18-calidad-aire-horario.zip",
    "2007": "https://datos.madrid.es/egob/catalogo/201200-17-calidad-aire-horario.zip",
    "2006": "https://datos.madrid.es/egob/catalogo/201200-16-calidad-aire-horario.zip",
    "2005": "https://datos.madrid.es/egob/catalogo/201200-15-calidad-aire-horario.zip",
    "2004": "https://datos.madrid.es/egob/catalogo/201200-14-calidad-aire-horario.zip",
    "2003": "https://datos.madrid.es/egob/catalogo/201200-13-calidad-aire-horario.zip",
    "2002": "https://datos.madrid.es/egob/catalogo/201200-30-calidad-aire-horario.zip",
    "2001": "https://datos.madrid.es/egob/catalogo/201200-29-calidad-aire-horario.zip"
}

magnitudes_map = {
    1: { "name": "Sulfur Dioxide", "abbreviation": "SO₂", "unit": "µg/m³", "method": "Ultraviolet Fluorescence" },
    6: { "name": "Carbon Monoxide", "abbreviation": "CO", "unit": "mg/m³", "method": "Infrared Absorption" },
    7: { "name": "Nitric Oxide", "abbreviation": "NO", "unit": "µg/m³", "method": "Chemiluminescence" },
    8: { "name": "Nitrogen Dioxide", "abbreviation": "NO₂", "unit": "µg/m³", "method": "Chemiluminescence" },
    9: { "name": "Particles < 2.5 µm", "abbreviation": "PM2.5", "unit": "µg/m³", "method": "Microbalance / Spectrometry" },
    10: { "name": "Particles < 10 µm", "abbreviation": "PM10", "unit": "µg/m³", "method": "Microbalance / Spectrometry" },
    12: { "name": "Nitrogen Oxides", "abbreviation": "NOx", "unit": "µg/m³", "method": "Chemiluminescence" },
    14: { "name": "Ozone", "abbreviation": "O₃", "unit": "µg/m³", "method": "Ultraviolet Absorption" },
    20: { "name": "Toluene", "abbreviation": "TOL", "unit": "µg/m³", "method": "Gas Chromatography" },
    30: { "name": "Benzene", "abbreviation": "BEN", "unit": "µg/m³", "method": "Gas Chromatography" },
    35: { "name": "Ethylbenzene", "abbreviation": "EBE", "unit": "µg/m³", "method": "Gas Chromatography" },
    37: { "name": "Metaxylene", "abbreviation": "MXY", "unit": "µg/m³", "method": "Gas Chromatography" },
    38: { "name": "Paraxylene", "abbreviation": "PXY", "unit": "µg/m³", "method": "Gas Chromatography" },
    39: { "name": "Orthoxylene", "abbreviation": "OXY", "unit": "µg/m³", "method": "Gas Chromatography" },
    42: { "name": "Total Hydrocarbons", "abbreviation": "TCH", "unit": "mg/m³", "method": "Gas Chromatography" },
    43: { "name": "Methane", "abbreviation": "CH₄", "unit": "mg/m³", "method": "Gas Chromatography" },
    44: { "name": "Non-methane Hydrocarbons", "abbreviation": "NMHC", "unit": "mg/m³", "method": "Gas Chromatography" },
    431: { "name": "Meta-Paraxylene", "abbreviation": "MPX", "unit": "mg/m³", "method": "Gas Chromatography" },
}